### PR TITLE
Cards and manifest changes

### PR DESCRIPTION
**Pull request by puddi**
@tjsnyder @M-Porter 

This updates the manifest by including scopes, removing some webhooks, and includes new dashboard cards. It also changes the OAuth router by not sending scopes in the first redirect (because they're no longer necessary.)

### CODE REVIEW

**Comment by puddi** [comment]
actually, the card means that there's an entire folder for the app required now.

**Comment by tjsnyder** [comment]
Two manifests with duplicate information now?

**Comment by puddi** [comment]
not anymore

**Comment by tjsnyder** [comment]
Sweet thanks!

**Pull request merged**
